apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
 name: kn-demo
 namespace: default
spec:
 template:
   spec:
     containerConcurrency: 5
     containers:
     - image: maeddes/simpleweb:v0.1
